# apply with "tmux source-file .tmux.conf"

# split pane
bind -N "Split window vertically" v split-window -h
bind -N "Split window horizontally" h split-window -v

# select next pane
bind -r -N "Select the next pane" b select-pane -t :.+
bind -r -N "Select the previous pane" B select-pane -t :.-

# resize pane
bind -r -N "Resize the pane down by 5" Down resize-pane -D 5
bind -r -N "Resize the pane up by 5" Up resize-pane -U 5
bind -r -N "Resize the pane left by 5" Left resize-pane -L 5
bind -r -N "Resize the pane right by 5" Right resize-pane -R 5

# Pane title
set -g pane-border-format "#{pane_index}: #{pane_current_command} #{pane_current_path}"

# move active pane to left top
bind -N "Move pane to index 0" ^ swap-pane -t 0 \; select-pane -t 0

# Pane Border
set -g pane-border-status top

# enter copy mode
bind -N "Enter copy mode" Escape copy-mode

# vim copy mode, yank with Enter
set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection

# start window index 1
set -g base-index 1

# rename window to dir
set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}"

# enable mouse support
set -g mouse on
